export const List = [
  {
    title: "Lost Wallet",
    location: "Downtown Park",
    reward: "$50",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/0000FF/808080?text=Lost+Wallet",
  },
  {
    title: "Found Keys",
    location: "City Mall",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FF0000/FFFFFF?text=Found+Keys",
  },
  {
    title: "Lost Dog",
    location: "Central Park",
    reward: "$200",
    type: "Lost",
    secondType: "Animal",
    photo: "https://via.placeholder.com/150/FFFF00/000000?text=Lost+Dog",
  },
  {
    title: "Found Sunglasses",
    location: "Sunny Beach",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo:
      "https://via.placeholder.com/150/00FF00/000000?text=Found+Sunglasses",
  },
  {
    title: "Lost Phone",
    location: "City Mall",
    reward: "$100",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FF00FF/FFFFFF?text=Lost+Phone",
  },
  {
    title: "Found Bicycle",
    location: "Train Station",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/00FFFF/000000?text=Found+Bicycle",
  },
  {
    title: "Lost Watch",
    location: "Local Gym",
    reward: "$75",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/0000FF/FFFFFF?text=Lost+Watch",
  },
  {
    title: "Found Backpack",
    location: "School Bus",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FF0000/000000?text=Found+Backpack",
  },
  {
    title: "Lost Cat",
    location: "Neighborhood",
    reward: "$150",
    type: "Lost",
    secondType: "Animal",
    photo: "https://via.placeholder.com/150/FFFF00/000000?text=Lost+Cat",
  },
  {
    title: "Found Jewelry",
    location: "City Park",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/00FF00/FFFFFF?text=Found+Jewelry",
  },
  {
    title: "Lost Laptop",
    location: "Coffee Shop",
    reward: "$300",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FF00FF/000000?text=Lost+Laptop",
  },
  {
    title: "Found Umbrella",
    location: "Bus Stop",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/00FFFF/FFFFFF?text=Found+Umbrella",
  },
  {
    title: "Lost Ring",
    location: "Beach",
    reward: "$100",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/0000FF/000000?text=Lost+Ring",
  },
  {
    title: "Found Scarf",
    location: "Library",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FF0000/FFFFFF?text=Found+Scarf",
  },
  {
    title: "Lost Glasses",
    location: "Office",
    reward: "$50",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FFFF00/000000?text=Lost+Glasses",
  },
  {
    title: "Found Shoes",
    location: "Local Gym",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/00FF00/000000?text=Found+Shoes",
  },
  {
    title: "Lost Jacket",
    location: "Concert Hall",
    reward: "$40",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FF00FF/FFFFFF?text=Lost+Jacket",
  },
  {
    title: "Found Book",
    location: "Coffee Shop",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/00FFFF/000000?text=Found+Book",
  },
  {
    title: "Lost Bracelet",
    location: "Fairground",
    reward: "$60",
    type: "Lost",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/0000FF/808080?text=Lost+Bracelet",
  },
  {
    title: "Found Hat",
    location: "Subway",
    reward: "None",
    type: "Found",
    secondType: "Object",
    photo: "https://via.placeholder.com/150/FF0000/FFFFFF?text=Found+Hat",
  },
];
